# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-02 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=15, null=True)),
                ('DNI', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('modify', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_edad', models.CharField(max_length=30)),
                ('franja_edad', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo_edad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Grupo_edad'),
        ),
        migrations.AddField(
            model_name='clase',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clase',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Year'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='clase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Clase'),
        ),
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together=set([('DNI', 'clase_id')]),
        ),
    ]
