# Generated by Django 3.0.6 on 2020-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_test_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
