# Generated by Django 3.0.6 on 2020-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_test_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='remote_id',
            field=models.IntegerField(null=True),
        ),
    ]
