# Generated by Django 3.0.6 on 2020-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0006_test_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='survey1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='survey2',
            field=models.BooleanField(default=False),
        ),
    ]
